/**
 * 系统工具技能包
 *
 * 覆盖：文件管理器、截图工具、控制面板、任务管理器、设置面板、
 * 记事本、计算器、画图、录音机、相机、照片、终端、注册表等
 * Windows 原生工具与系统操控。
 */
import type { SkillPack } from '../types'

export const systemSkillPack: SkillPack = {
  id: 'system.native',
  app: '系统工具',
  appMatch: ['系统', 'Windows', '设置', '任务管理器', '控制面板', '资源管理器', '文件管理器',
    '注册表', '终端', '命令提示符', '记事本', '计算器', '画图', '截图', '磁盘', '设备管理器',
    '放大镜', '便笺', '时钟', '相机', '录音机', '照片', '性能', '事件', '服务', '计划任务', '剪贴板'],
  version: '1.0.0',
  actions: [
    {
      id: 'open_file_explorer',
      name: '打开文件管理器',
      description: '打开文件资源管理器窗口',
      keywords: ['文件管理器', '资源管理器', '打开文件夹', '我的电脑', '此电脑'],
      hints: [
        '快捷键 Win+E 直接打开文件资源管理器',
        '若需打开指定目录，可在地址栏输入路径后回车',
      ],
      shortcuts: ['Win+E'],
      verifyHint: '确认文件资源管理器窗口已显示',
    },
    {
      id: 'open_snipping',
      name: '打开截图工具',
      description: '打开系统截图工具',
      keywords: ['截图', '截屏', '截图工具', 'snipping'],
      hints: [
        'Win+Shift+S 直接进入截图选区模式',
        '截图工具支持矩形/任意形状/窗口/全屏四种模式',
      ],
      shortcuts: ['Win+Shift+S'],
      verifyHint: '确认截图工具界面或截图选区已出现',
    },
    {
      id: 'open_control_panel',
      name: '打开控制面板',
      description: '打开经典控制面板',
      keywords: ['控制面板', '控制台'],
      hints: [
        'Win+R 输入 control 回车可打开控制面板',
        '经典控制面板与设置应用为两个不同入口',
      ],
      shortcuts: ['Win+R → control'],
      verifyHint: '确认控制面板窗口已显示',
    },
    {
      id: 'open_task_manager',
      name: '打开任务管理器',
      description: '打开任务管理器查看进程/性能',
      keywords: ['任务管理器', '进程', 'cpu', '内存', '性能'],
      hints: [
        '快捷键 Ctrl+Shift+Esc 直接打开',
        '底部"详细信息"可展开完整进程列表',
      ],
      shortcuts: ['Ctrl+Shift+Esc'],
      verifyHint: '确认任务管理器窗口已显示',
    },
    {
      id: 'open_settings',
      name: '打开设置',
      description: '打开 Windows 设置应用',
      keywords: ['设置', '系统设置', 'windows设置'],
      hints: [
        '快捷键 Win+I 打开系统设置',
        '设置首页可进入系统/设备/网络/个性化等分区',
      ],
      shortcuts: ['Win+I'],
      verifyHint: '确认设置窗口已显示',
    },
    {
      id: 'open_notepad',
      name: '打开记事本',
      description: '打开记事本应用',
      keywords: ['记事本', '文本编辑', 'notepad', '新建文本'],
      hints: [
        'Win+R 输入 notepad 回车即可打开',
        '记事本支持 Markdown 预览（新版）',
      ],
      shortcuts: ['Win+R → notepad'],
      verifyHint: '确认记事本窗口已显示',
    },
    {
      id: 'open_calculator',
      name: '打开计算器',
      description: '打开计算器应用',
      keywords: ['计算器', 'calc', '计算'],
      hints: [
        'Win+R 输入 calc 回车即可打开',
        '支持标准/科学/程序员/日期计算四种模式',
      ],
      shortcuts: ['Win+R → calc'],
      verifyHint: '确认计算器窗口已显示',
    },
    {
      id: 'open_paint',
      name: '打开画图',
      description: '打开画图应用',
      keywords: ['画图', 'mspaint', '绘图'],
      hints: [
        'Win+R 输入 mspaint 回车即可打开',
        '新版画图支持图层与 AI 橡皮擦',
      ],
      shortcuts: ['Win+R → mspaint'],
      verifyHint: '确认画图窗口已显示',
    },
    {
      id: 'open_cmd',
      name: '打开命令提示符',
      description: '打开命令提示符窗口',
      keywords: ['命令提示符', 'cmd', '命令行', '终端'],
      hints: [
        'Win+R 输入 cmd 回车即可打开',
        '需要管理员权限时用 Ctrl+Shift+Enter 以管理员运行',
      ],
      shortcuts: ['Win+R → cmd'],
      verifyHint: '确认命令提示符窗口已显示',
    },
    {
      id: 'open_regedit',
      name: '打开注册表编辑器',
      description: '打开注册表编辑器',
      keywords: ['注册表', 'regedit', '注册表编辑器'],
      hints: [
        'Win+R 输入 regedit 回车即可打开',
        '修改注册表前务必先导出备份',
        '若 UAC 弹窗需确认允许',
      ],
      shortcuts: ['Win+R → regedit'],
      verifyHint: '确认注册表编辑器窗口已显示',
    },
    {
      id: 'open_device_manager',
      name: '打开设备管理器',
      description: '打开设备管理器',
      keywords: ['设备管理器', '驱动', '硬件'],
      hints: [
        'Win+R 输入 devmgmt.msc 回车即可打开',
        '可按类别查看所有硬件设备状态',
      ],
      shortcuts: ['Win+R → devmgmt.msc'],
      verifyHint: '确认设备管理器窗口已显示',
    },
    {
      id: 'open_disk_management',
      name: '打开磁盘管理',
      description: '打开磁盘管理工具',
      keywords: ['磁盘管理', '硬盘', '分区'],
      hints: [
        'Win+R 输入 diskmgmt.msc 回车即可打开',
        '可查看磁盘容量与分区布局',
      ],
      shortcuts: ['Win+R → diskmgmt.msc'],
      verifyHint: '确认磁盘管理窗口已显示',
    },
    {
      id: 'open_event_viewer',
      name: '打开事件查看器',
      description: '打开事件查看器',
      keywords: ['事件查看器', '日志', 'event'],
      hints: [
        'Win+R 输入 eventvwr.msc 回车即可打开',
        'Windows 日志下可查看系统/应用错误记录',
      ],
      shortcuts: ['Win+R → eventvwr.msc'],
      verifyHint: '确认事件查看器窗口已显示',
    },
    {
      id: 'open_terminal',
      name: '打开终端',
      description: '打开 Windows Terminal',
      keywords: ['终端', 'windows terminal', 'powershell'],
      hints: [
        'Win+R 输入 wt 回车即可打开 Windows Terminal',
        '默认打开 PowerShell，可切换 CMD/其他配置',
      ],
      shortcuts: ['Win+R → wt'],
      verifyHint: '确认终端窗口已显示',
    },
    {
      id: 'open_voice_recorder',
      name: '打开录音机',
      description: '打开录音机应用',
      keywords: ['录音', '录音机', '语音录制'],
      hints: [
        '从开始菜单或搜索"录音机"打开',
        '点击红色按钮开始录制',
      ],
      shortcuts: [],
      verifyHint: '确认录音机窗口已显示',
    },
    {
      id: 'open_camera',
      name: '打开相机',
      description: '打开相机应用',
      keywords: ['相机', '拍照', '摄像头'],
      hints: [
        '从开始菜单或搜索"相机"打开',
        '相机打开后自动进入取景状态',
      ],
      shortcuts: [],
      verifyHint: '确认相机取景画面已出现',
    },
    {
      id: 'open_photos',
      name: '打开照片',
      description: '打开照片应用查看图片',
      keywords: ['照片', '图片查看', '照片查看器'],
      hints: [
        '从开始菜单或搜索"照片"打开',
        '也可直接双击图片文件打开',
      ],
      shortcuts: [],
      verifyHint: '确认照片应用已打开',
    },
    {
      id: 'open_magnifier',
      name: '打开放大镜',
      description: '打开屏幕放大镜',
      keywords: ['放大镜', '放大', '屏幕放大'],
      hints: [
        '快捷键 Win+加号(+) 直接打开放大镜',
        'Win+减号(-) 缩小，Win+Esc 退出',
      ],
      shortcuts: ['Win+加号', 'Win+减号', 'Win+Esc'],
      verifyHint: '确认放大镜已启动',
    },
    {
      id: 'open_sticky_notes',
      name: '打开便笺',
      description: '打开便笺应用',
      keywords: ['便笺', '便签', 'sticky note', '笔记'],
      hints: [
        '从开始菜单或搜索"便笺"打开',
        '便笺内容自动同步到微软账号',
      ],
      shortcuts: [],
      verifyHint: '确认便笺应用已打开',
    },
    {
      id: 'open_clock',
      name: '打开时钟',
      description: '打开时钟应用',
      keywords: ['时钟', '闹钟', '计时器', '秒表'],
      hints: [
        '从开始菜单或搜索"时钟"打开',
        '包含闹钟/计时器/秒表/世界时钟',
      ],
      shortcuts: [],
      verifyHint: '确认时钟应用已打开',
    },
    {
      id: 'open_task_scheduler',
      name: '打开任务计划程序',
      description: '打开任务计划程序',
      keywords: ['计划任务', '任务计划', '定时任务'],
      hints: [
        'Win+R 输入 taskschd.msc 回车即可打开',
        '可在其中创建系统定时任务',
      ],
      shortcuts: ['Win+R → taskschd.msc'],
      verifyHint: '确认任务计划程序窗口已显示',
    },
    {
      id: 'open_perfmon',
      name: '打开性能监视器',
      description: '打开性能监视器',
      keywords: ['性能监视器', '性能', 'perfmon'],
      hints: [
        'Win+R 输入 perfmon 回车即可打开',
        '可监控 CPU/内存/磁盘/网络计数器',
      ],
      shortcuts: ['Win+R → perfmon'],
      verifyHint: '确认性能监视器窗口已显示',
    },
    {
      id: 'open_resmon',
      name: '打开资源监视器',
      description: '打开资源监视器',
      keywords: ['资源监视器', '资源', 'resmon'],
      hints: [
        'Win+R 输入 resmon 回车即可打开',
        '可查看进程 CPU/磁盘/网络/内存占用',
      ],
      shortcuts: ['Win+R → resmon'],
      verifyHint: '确认资源监视器窗口已显示',
    },
    {
      id: 'toggle_mute',
      name: '静音/取消静音',
      description: '切换系统静音状态',
      keywords: ['静音', '音量', '喇叭', '扬声器', 'mute'],
      hints: [
        '部分键盘有静音多媒体键',
        '也可通过 Win+R 输入 mmsys.cpl 打开音量设置',
      ],
      shortcuts: ['静音键'],
      verifyHint: '确认系统音量状态已切换',
    },
    {
      id: 'show_desktop',
      name: '显示桌面',
      description: '最小化所有窗口显示桌面',
      keywords: ['显示桌面', '桌面', '最小化所有'],
      hints: [
        '快捷键 Win+D 显示桌面',
        '再次按 Win+D 恢复原窗口',
      ],
      shortcuts: ['Win+D'],
      verifyHint: '确认桌面已显示',
    },
    {
      id: 'lock_screen',
      name: '锁定电脑',
      description: '锁定当前电脑',
      keywords: ['锁定', '锁屏', '锁电脑', '离开'],
      hints: [
        '快捷键 Win+L 立即锁定电脑',
        '锁定后需要密码/指纹解锁',
      ],
      shortcuts: ['Win+L'],
      verifyHint: '确认已回到锁屏界面',
    },
    {
      id: 'switch_window',
      name: '切换窗口',
      description: '在打开的窗口间切换',
      keywords: ['切换窗口', '切换', 'alt tab'],
      hints: [
        'Alt+Tab 打开窗口切换器，松开即切到当前高亮窗口',
        'Alt+Tab 按住不放可用方向键选择',
      ],
      shortcuts: ['Alt+Tab'],
      verifyHint: '确认已切换到目标窗口',
    },
    {
      id: 'open_search',
      name: '打开搜索',
      description: '打开 Windows 搜索',
      keywords: ['搜索', '查找', 'win s', '搜索栏'],
      hints: [
        '快捷键 Win+S 打开搜索面板',
        '搜索框支持应用/文件/网页/设置全能检索',
      ],
      shortcuts: ['Win+S'],
      verifyHint: '确认搜索面板已打开',
    },
    {
      id: 'open_run',
      name: '打开运行对话框',
      description: '打开运行对话框',
      keywords: ['运行', 'win r', '运行框'],
      hints: [
        '快捷键 Win+R 打开运行对话框',
        '可输入命令快速启动程序',
      ],
      shortcuts: ['Win+R'],
      verifyHint: '确认运行对话框已打开',
    },
    {
      id: 'open_clipboard',
      name: '打开剪贴板',
      description: '打开剪贴板历史',
      keywords: ['剪贴板', '粘贴历史', 'clipboard'],
      hints: [
        '快捷键 Win+V 打开剪贴板历史',
        '首次使用需在设置中开启剪贴板历史',
      ],
      shortcuts: ['Win+V'],
      verifyHint: '确认剪贴板面板已打开',
    },
    {
      id: 'new_virtual_desktop',
      name: '新建虚拟桌面',
      description: '创建新的虚拟桌面',
      keywords: ['新建桌面', '虚拟桌面', '新桌面'],
      hints: [
        '快捷键 Ctrl+Win+D 新建虚拟桌面',
        '任务视图 Win+Tab 可管理多个桌面',
      ],
      shortcuts: ['Ctrl+Win+D'],
      verifyHint: '确认已进入新虚拟桌面',
    },
    {
      id: 'switch_virtual_desktop',
      name: '切换虚拟桌面',
      description: '在虚拟桌面之间切换',
      keywords: ['上一个桌面', '下一个桌面', '切换桌面'],
      hints: [
        'Ctrl+Win+左/右 切换虚拟桌面',
        '也可在任务视图中用鼠标选择',
      ],
      shortcuts: ['Ctrl+Win+左/右'],
      verifyHint: '确认已切换到目标虚拟桌面',
    },
    {
      id: 'close_window',
      name: '关闭当前窗口',
      description: '关闭当前活动窗口',
      keywords: ['关闭窗口', '关闭', '退出'],
      hints: [
        '快捷键 Alt+F4 关闭当前窗口',
        '若在桌面按 Alt+F4 会弹出关机对话框',
      ],
      shortcuts: ['Alt+F4'],
      verifyHint: '确认目标窗口已关闭',
    },
    {
      id: 'minimize_window',
      name: '最小化窗口',
      description: '最小化当前活动窗口',
      keywords: ['最小化', '缩小'],
      hints: [
        '快捷键 Win+下箭头 最小化当前窗口',
        '再次按 Win+下箭头 可恢复',
      ],
      shortcuts: ['Win+↓'],
      verifyHint: '确认窗口已最小化到任务栏',
    },
    {
      id: 'maximize_window',
      name: '最大化窗口',
      description: '最大化当前活动窗口',
      keywords: ['最大化', '全屏'],
      hints: [
        '快捷键 Win+上箭头 最大化当前窗口',
        '再次按 Win+上箭头 可还原',
      ],
      shortcuts: ['Win+↑'],
      verifyHint: '确认窗口已最大化',
    },
    {
      id: 'snap_left',
      name: '分屏到左侧',
      description: '将当前窗口分屏到屏幕左侧',
      keywords: ['分屏左', '左半屏', '左侧分屏'],
      hints: [
        '快捷键 Win+左箭头 分屏到左侧',
        '随后可用 Win+上/下 选择上/下象限',
      ],
      shortcuts: ['Win+←'],
      verifyHint: '确认窗口已停靠在左侧',
    },
    {
      id: 'snap_right',
      name: '分屏到右侧',
      description: '将当前窗口分屏到屏幕右侧',
      keywords: ['分屏右', '右半屏', '右侧分屏'],
      hints: [
        '快捷键 Win+右箭头 分屏到右侧',
        '随后可用 Win+上/下 选择上/下象限',
      ],
      shortcuts: ['Win+→'],
      verifyHint: '确认窗口已停靠在右侧',
    },
    {
      id: 'open_task_view',
      name: '打开任务视图',
      description: '打开任务视图/时间线',
      keywords: ['任务视图', '时间线', 'timeline'],
      hints: [
        '快捷键 Win+Tab 打开任务视图',
        '可查看所有窗口与虚拟桌面',
      ],
      shortcuts: ['Win+Tab'],
      verifyHint: '确认任务视图已打开',
    },
    {
      id: 'open_game_bar',
      name: '打开游戏栏',
      description: '打开 Xbox Game Bar',
      keywords: ['游戏栏', 'xbox', 'game bar', '录制'],
      hints: [
        '快捷键 Win+G 打开游戏栏',
        '支持录屏、性能监控、小组件',
      ],
      shortcuts: ['Win+G'],
      verifyHint: '确认游戏栏已打开',
    },
    {
      id: 'open_notification_center',
      name: '打开通知中心',
      description: '打开操作中心/通知中心',
      keywords: ['通知', '通知中心', '日历', '操作中心'],
      hints: [
        '快捷键 Win+A 打开操作中心',
        '包含通知列表与快捷设置',
      ],
      shortcuts: ['Win+A'],
      verifyHint: '确认操作中心已打开',
    },
    {
      id: 'open_connect',
      name: '打开蓝牙连接',
      description: '打开蓝牙/设备连接面板',
      keywords: ['蓝牙', '蓝牙设置', '连接设备'],
      hints: [
        '快捷键 Win+K 打开蓝牙连接面板',
        '可快速配对蓝牙设备',
      ],
      shortcuts: ['Win+K'],
      verifyHint: '确认蓝牙连接面板已打开',
    },
    {
      id: 'open_project',
      name: '打开投影设置',
      description: '打开投影/投屏设置',
      keywords: ['投影', '投屏', '扩展屏幕', '复制屏幕'],
      hints: [
        '快捷键 Win+P 打开投影设置',
        '可选仅电脑屏幕/复制/扩展/仅第二屏幕',
      ],
      shortcuts: ['Win+P'],
      verifyHint: '确认投影设置面板已打开',
    },
  ],
}